CREATE TABLE Balance_Sheet (
  ID INT AUTO_INCREMENT,
  cik INT NOT NULL,
  calendarYear VARCHAR(5) NOT NULL,
  period VARCHAR(5) NOT NULL,
  cashAndCashEquivalents DECIMAL(20,4),
  shortTermInvestments DECIMAL(20,4),
  cashAndShortTermInvestments DECIMAL(20,4),
  netReceivables DECIMAL(20,4),
  inventory DECIMAL(20,4),
  otherCurrentAssets DECIMAL(20,4),
  totalCurrentAssets DECIMAL(20,4),
  propertyPlantEquipmentNet DECIMAL(20,4),
  goodwill DECIMAL(20,4),
  intangibleAssets DECIMAL(20,4),
  goodwillAndIntangibleAssets DECIMAL(20,4),
  longTermInvestments DECIMAL(20,4),
  taxAssets DECIMAL(20,4),
  otherNonCurrentAssets DECIMAL(20,4),
  totalNonCurrentAssets DECIMAL(20,4),
  otherAssets DECIMAL(20,4),
  totalAssets DECIMAL(20,4),
  accountPayables DECIMAL(20,4),
  shortTermDebt DECIMAL(20,4),
  taxPayables DECIMAL(20,4),
  deferredRevenue DECIMAL(20,4),
  otherCurrentLiabilities DECIMAL(20,4),
  totalCurrentLiabilities DECIMAL(20,4),
  longTermDebt DECIMAL(20,4),
  deferredRevenueNonCurrent DECIMAL(20,4),
  deferredTaxLiabilitiesNonCurrent DECIMAL(20,4),
  otherNonCurrentLiabilities DECIMAL(20,4),
  totalNonCurrentLiabilities DECIMAL(20,4),
  otherLiabilities DECIMAL(20,4),
  capitalLeaseObligations DECIMAL(20,4),
  totalLiabilities DECIMAL(20,4),
  preferredStock DECIMAL(20,4),
  commonStock DECIMAL(20,4),
  retainedEarnings DECIMAL(20,4),
  accumulatedOtherComprehensiveIncomeLoss DECIMAL(20,4),
  othertotalStockholdersEquity DECIMAL(20,4),
  totalStockholdersEquity DECIMAL(20,4),
  totalEquity DECIMAL(20,4),
  totalLiabilitiesAndStockholdersEquity DECIMAL(20,4),
  minorityInterest DECIMAL(20,4),
  totalLiabilitiesAndTotalEquity DECIMAL(20,4),
  totalInvestments DECIMAL(20,4),
  totalDebt DECIMAL(20,4),
  netDebt DECIMAL(20,4),
  KEY(ID),
  PRIMARY KEY (ID, cik, calendarYear, period)
);