CREATE TABLE Cashflow_Statement (
    ID INT NOT NULL AUTO_INCREMENT,
    cik INT NOT NULL,
    calendarYear VARCHAR(5),
    period VARCHAR(5),
    netIncome DECIMAL(24,4),
    depreciationAndAmortization DECIMAL(24,4),
    deferredIncomeTax DECIMAL(24,4),
    stockBasedCompensation DECIMAL(24,4),
    changeInWorkingCapital DECIMAL(24,4),
    accountsReceivables DECIMAL(24,4),
    inventory DECIMAL(24,4),
    accountsPayables DECIMAL(24,4),
    otherWorkingCapital DECIMAL(24,4),
    otherNonCashItems DECIMAL(24,4),
    netCashProvidedByOperatingActivities DECIMAL(24,4),
    investmentsInPropertyPlantAndEquipment DECIMAL(24,4),
    acquisitionsNet DECIMAL(24,4),
    purchasesOfInvestments DECIMAL(24,4),
    salesMaturitiesOfInvestments DECIMAL(24,4),
    otherInvestingActivites DECIMAL(24,4),
    netCashUsedForInvestingActivites DECIMAL(24,4),
    debtRepayment DECIMAL(24,4),
    commonStockIssued DECIMAL(24,4),
    commonStockRepurchased DECIMAL(24,4),
    dividendsPaid DECIMAL(24,4),
    otherFinancingActivites DECIMAL(24,4),
    netCashUsedProvidedByFinancingActivities DECIMAL(24,4),
    effectOfForexChangesOnCash DECIMAL(24,4),
    netChangeInCash DECIMAL(24,4),
    cashAtEndOfPeriod DECIMAL(24,4),
    cashAtBeginningOfPeriod DECIMAL(24,4),
    operatingCashFlow DECIMAL(24,4),
    capitalExpenditure DECIMAL(24,4),
    freeCashFlow DECIMAL(24,4),
    KEY(ID),
    PRIMARY KEY (cik, calendarYear, period)
);
