CREATE TABLE Income_Statement (
  ID INT NOT NULL AUTO_INCREMENT,
  cik INT NOT NULL,
  calendarYear VARCHAR(5) NOT NULL,
  period VARCHAR(5) NOT NULL,
  revenue DECIMAL(20,4),
  costOfRevenue DECIMAL(20,4),
  grossProfit DECIMAL(20,4),
  researchAndDevelopmentExpenses DECIMAL(20,4),
  generalAndAdministrativeExpenses DECIMAL(20,4),
  sellingAndMarketingExpenses DECIMAL(20,4),
  sellingGeneralAndAdministrativeExpenses DECIMAL(20,4),
  otherExpenses DECIMAL(20,4),
  operatingExpenses DECIMAL(20,4),
  costAndExpenses DECIMAL(20,4),
  interestIncome DECIMAL(20,4),
  interestExpense DECIMAL(20,4),
  depreciationAndAmortization DECIMAL(20,4),
  ebitda DECIMAL(20,4),
  operatingIncome DECIMAL(20,4),
  totalOtherIncomeExpensesNet DECIMAL(20,4),
  incomeBeforeTax DECIMAL(20,4),
  incomeTaxExpense DECIMAL(20,4),
  netIncome DECIMAL(20,4),
  KEY(ID),
  PRIMARY KEY (cik, calendarYear, period, ID)
);